version: "3.3"
services:
  pandare:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "4443:5900"
    volumes:
      - "./docker/dev:/addon"
      - "./docker/.panda:/root/.panda"
      - "./payload:/payload"
      - "./output:/output"
      - "./.debug:/debug"
      - "./replay:/replay"
    environment:
      - panda_debug=True
      - panda_memcheck=False
      - panda_entropy=False
      - panda_dll=True
      - panda_dll_discover=True
      - panda_section_perms=True
      - panda_first_bytes=True
      #- panda_executable=upx_ADExplorer.exe
      #- panda_max_entropy_list_length=50
    command: "python3 /addon/read_replay.py upx_ADExplorer.exe"
    #command: "python3 /addon/discover_dlls.py"
