version: "3.3"
services:
  pandare:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - "/.debug:/debug"
      - "./payload:/payload"
      - "./additional-dll:/additional-dll"
    environment:
      - panda_silent=False